services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/02_seguridad/Dockerfile
    container_name: cttomasseguridad
    image: mtomasnievasm/ubseguridad
    ports:
      - 3457:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs