services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/03_ngnix/Dockerfile
    container_name: cttomasnginx
    image: mtomasnievasm/ubnginx
    ports:
      - "80:80"
      - "3458:22"
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs